### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by marktani** [graphcool-examples/vue-graphql#16]
![image](https://cloud.githubusercontent.com/assets/1780597/26532268/7ec3cbfa-43fc-11e7-921b-a23dd0338f78.png)

**Comment by stubailo** [comment]
I think there were a few changes in the library since this example was created, probably worth reaching out to the author of the integration!

**Comment by marktani** [comment]
Thanks for the idea! But @gmanfredi was quicker 🏃 👍
